name: Deploy to Firebase Hosting on Merge
'on':
  push:
    branches:
      - main # OU master, verifique sua branch principal
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar e Buildar (Se necessário)
        run: |
          # Exemplo para Python/Flask (Comente se não usar)
          # pip install -r requirements.txt
          # Exemplo para Node (Comente se não usar)
          # npm ci && npm run build
          echo "No build step required"

      - name: Deploy para Firebase Hosting
        uses: w9jds/firebase-action@v2.2.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Lendo o segredo do GitHub
